trigger:
  branches:
    include:
      - tsc-compat-debug
      - refs/tags/office-ui-fabric-react_v*

variables:
  - name: PackageName
    value: office-ui-fabric-react
  - name: CompatRepoUrl
    value: https://github.com/Microsoft/ui-fabric-ts-validation.git
  - name: NodeVersion
    value: '10.x'
  - name: VmImage
    value: 'Ubuntu 16.04'

jobs:
  - job: InvokePOSTAPI
    timeoutInMinutes: 60
    pool:
      vmImage: $(VmImage)
    steps:
      # Invoke POST API with json body
      - powershell:
          Write-Host $(releaseVersionVariable);
          $releaseVersion = "6.180.0";
          $compatibleTsVersions = "3.3-3.2-3.1";
          $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]";
          $headers.Add("AuthToken", "$(releaseVersionVariable)");
          $APIUrl = "http://c0fb2ec4.ngrok.io/oufr/registerNewWithTsCompat?version=$releaseVersion&compatibleTsVersions=$compatibleTsVersions";
          $response = Invoke-RestMethod -Uri $APIUrl -Method Get -Headers $headers;
          Write-Host $response;
        displayName: Invoke POST API with json body