trigger:
  branches:
    include:
      - tsc-compat-debug
      - refs/tags/office-ui-fabric-react_v*

variables:
  - name: PackageName
    value: office-ui-fabric-react
  - name: CompatRepoUrl
    value: https://github.com/Microsoft/ui-fabric-ts-validation.git
  - name: NodeVersion
    value: '10.x'
  - name: VmImage
    value: 'Ubuntu 16.04'

jobs:
  - job: Build
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 60
    steps:
      - checkout: self
        clean: true

      - task: NodeTool@0
        displayName: 'Use Node $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'
          checkLatest: true

      - script: echo "Aftab Test"

     # Invoke POST REST API
      - powershell:
          $person = @{
            first='joe';
            lastname='doe'
          }
          $body = (ConvertTo-Json $person)
          $response = Invoke-RestMethod 'https://jsonplaceholder.typicode.com/posts' -Method Put -Body $json -ContentType 'application/json'
          echo $response
        name: InvokeTypicodeAPI
        displayName: Invoke Typicode API  