trigger:
  branches:
    include:
      - tsc-compat-debug
      - refs/tags/office-ui-fabric-react_v*

variables:
  - name: PackageName
    value: office-ui-fabric-react
  - name: CompatRepoUrl
    value: https://github.com/Microsoft/ui-fabric-ts-validation.git
  - name: NodeVersion
    value: '10.x'
  - name: VmImage
    value: 'Ubuntu 16.04'

jobs:
  - job: Compatibility
    timeoutInMinutes: 60
    pool:
      vmImage: $(VmImage)
    strategy:
      maxParallel: 2
      matrix:
        # 'TypeScript_2.4':
        #   TypeScriptVersion: 2.4
        # 'TypeScript_2.7':
        #   TypeScriptVersion: 2.7
        # 'TypeScript_2.9':
        #   TypeScriptVersion: 2.9
        # 'TypeScript_3.0':
        #   TypeScriptVersion: 3.0
        # 'TypeScript_3.1':
        #   TypeScriptVersion: 3.1
        # 'TypeScript_3.2':
        #   TypeScriptVersion: 3.2
        # 'TypeScript_3.3':
        #   TypeScriptVersion: 3.3
        'TypeScript_3.4':
          TypeScriptVersion: 3.4
    steps:
      - checkout: none
      - task: NodeTool@0
        displayName: 'Use Node $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'
          checkLatest: true

      # Only moving to drop2 
      - script: |
          $params = @{ To = "+15558675309"; From = $number; Body = "Hello from PowerShell" }
          echo $params
        name: InvokeTypicodeAPI
        displayName: Invoke Typicode API  
